language: php

php:
  - 5.5
  - 5.6
  - 7.2

before_script:
  - sudo -E su root -c 'apt-get update'
  - sudo -E su root -c 'apt-get install -y software-properties-common'
  - sudo -E su root -c 'apt-get install -y python-software-properties python g++ make'
  - sudo -E su root -c 'apt-add-repository -y ppa:chris-lea/node.js'
  - sudo -E su root -c 'apt-get update'
  - sudo -E su root -c 'apt-get install -y nodejs'
  - sudo -E su root -c 'npm install -g grunt-cli'
  - npm install
  - composer self-update
  - composer install --dev --no-interaction

script: ./bin/atoum && grunt lint
